package com.paymentpage.msdk.ui

object TestTagsConstants {
    //Common
    const val PREFIX_SAVE_CARD = "SAVE_CARD_"
    const val PREFIX_NEW_CARD = "NEW_CARD_"
    const val PREFIX_GOOGLE_PAY = "GOOGLE_PAY_"
    const val PREFIX_APS = "APS_"

    const val POSTFIX_CUSTOMER_FIELD = "_CUSTOMER_FIELD"
    private const val POSTFIX_REGULAR = "_REGULAR"
    private const val POSTFIX_EXPRESS = "_EXPRESS"
    const val POSTFIX_LINK = "_LINK"
    const val POSTFIX_ICON = "_ICON"
    const val POSTFIX_DEFAULT = "_DEFAULT"
    const val POSTFIX_LOCAL = "_LOCAL"
    const val POSTFIX_REMOTE = "_REMOTE"

    const val POSTFIX_TEXT = "_TEXT"
    private const val POSTFIX_BUTTON = "_BUTTON"
    private const val POSTFIX_TEXT_FIELD = "_TEXT_FIELD"

    const val POSTFIX_LABEL = "_LABEL"
    const val POSTFIX_VALUE = "_VALUE"

    const val DARK_THEME = "DARK"
    const val LIGHT_THEME = "LIGHT"
    const val FREE_SPACE_CLOSE_PAYMENT_BUTTON = "FREE_SPACE_CLOSE_PAYMENT$POSTFIX_BUTTON"

    const val FOOTER_IMAGE = "FOOTER_IMAGE"
    const val LOGO_IMAGE = "LOGO_IMAGE"
    const val LANGUAGE_ICON = "LANGUAGE_ICON"

    //Text
    const val SCREEN_TITLE_TEXT = "SCREEN_TITLE$POSTFIX_TEXT"
    const val FOOTER_LABEL_TEXT = "FOOTER$POSTFIX_LABEL$POSTFIX_TEXT"

    const val COINS_VALUE_TEXT = "COINS$POSTFIX_VALUE$POSTFIX_TEXT"
    const val CURRENCY_VALUE_TEXT = "CURRENCY$POSTFIX_VALUE$POSTFIX_TEXT"
    const val LANGUAGE_VALUE_TEXT = "LANGUAGE$POSTFIX_VALUE$POSTFIX_TEXT"
    const val PAYMENT_ID_LABEL_TEXT = "PAYMENT_ID$POSTFIX_LABEL$POSTFIX_TEXT"
    const val PAYMENT_ID_VALUE_TEXT = "PAYMENT_ID$POSTFIX_VALUE$POSTFIX_TEXT"
    const val PAYMENT_DESCRIPTION_LABEL_TEXT = "PAYMENT_DESCRIPTION$POSTFIX_LABEL$POSTFIX_TEXT"
    const val PAYMENT_DESCRIPTION_VALUE_TEXT = "PAYMENT_DESCRIPTION$POSTFIX_VALUE$POSTFIX_TEXT"
    const val PAYMENT_DETAILS_LABEL_TEXT = "PAYMENT_DETAILS$POSTFIX_LABEL$POSTFIX_TEXT"
    const val ADDRESS_LABEL_TEXT = "ADDRESS$POSTFIX_LABEL$POSTFIX_TEXT"
    const val ADDRESS_VALUE_TEXT = "ADDRESS$POSTFIX_VALUE$POSTFIX_TEXT"
    const val RECURRING_AGREEMENTS_REGULAR_LABEL_TEXT =
        "RECURRING_AGREEMENTS$POSTFIX_REGULAR$POSTFIX_LABEL$POSTFIX_TEXT"
    const val RECURRING_AGREEMENTS_EXPRESS_LABEL_TEXT =
        "RECURRING_AGREEMENTS$POSTFIX_EXPRESS$POSTFIX_LABEL$POSTFIX_TEXT"

    const val PAYMENT_METHOD_ITEM_TITLE_TEXT = "PAYMENT_METHOD_ITEM_TITLE$POSTFIX_TEXT"
    const val PAYMENT_METHOD_ITEM_SECTION = "PAYMENT_METHOD_ITEM_SECTION"
    const val APS_PAYMENT_DISCLAIMER_TEXT = "${PREFIX_APS}PAYMENT_DISCLAIMER$POSTFIX_TEXT"

    const val LOADING_TITLE_TEXT = "LOADING_TITLE$POSTFIX_TEXT"
    const val LOADING_SUB_TITLE_TEXT = "LOADING_SUB_TITLE$POSTFIX_TEXT"

    const val ADDITIONAL_DATA_DISCLAIMER_TEXT = "ADDITIONAL_DATA_DISCLAIMER$POSTFIX_TEXT"

    const val BUTTON_CURRENCY_TEXT = "BUTTON_CURRENCY$POSTFIX_TEXT"
    const val BUTTON_AMOUNT_TEXT = "BUTTON_AMOUNT$POSTFIX_TEXT"
    const val BUTTON_LABEL_TEXT = "BUTTON_LABEL$POSTFIX_TEXT"

    //Text fields
    const val CVV_TEXT_FIELD = "CVV$POSTFIX_TEXT_FIELD"
    const val EXPIRY_TEXT_FIELD = "EXPIRY$POSTFIX_TEXT_FIELD"
    const val CARDHOLDER_TEXT_FIELD = "CARDHOLDER$POSTFIX_TEXT_FIELD"
    const val PAN_TEXT_FIELD = "PAN$POSTFIX_TEXT_FIELD"

    //Buttons
    const val SCREEN_CLOSE_BUTTON = "SCREEN_CLOSE$POSTFIX_BUTTON"
    const val SCREEN_BACK_BUTTON = "SCREEN_BACK$POSTFIX_BUTTON"
    const val PAYMENT_DETAILS_BUTTON = "PAYMENT_DETAILS$POSTFIX_BUTTON"
    const val SAVE_BUTTON = "SAVE$POSTFIX_BUTTON"
    const val AUTHORIZE_BUTTON = "AUTHORIZE$POSTFIX_BUTTON"
    const val PAY_BUTTON = "PAY$POSTFIX_BUTTON"
    const val PROCEED_BUTTON = "PROCEED$POSTFIX_BUTTON"
    const val CONFIRMATION_BUTTON = "CONFIRMATION$POSTFIX_BUTTON"
    const val CLOSE_BUTTON = "CLOSE$POSTFIX_BUTTON"
    const val TRY_AGAIN_BUTTON = "TRY_AGAIN$POSTFIX_BUTTON"
    const val DONE_BUTTON = "DONE$POSTFIX_BUTTON"
    const val GOOGLE_PAY_BUTTON = "GOOGLE_PAY$POSTFIX_BUTTON"
    const val CARD_SCANNING_BUTTON = "CARD_SCANNING$POSTFIX_BUTTON"
    const val DELETE_CARD_BUTTON = "DELETE_CARD$POSTFIX_BUTTON"
    const val CVV_INFO_BUTTON = "CVV_INFO$POSTFIX_BUTTON"
    const val CANCEL_PAYMENT_BUTTON = "CANCEL_PAYMENT$POSTFIX_BUTTON"
}
