package com.paymentpage.msdk.ui

object TestTagsConstants {
    //Common
    const val PREFIX_SAVE_CARD = "SAVE_CARD_"
    const val PREFIX_NEW_CARD = "NEW_CARD_"
    const val POSTFIX_CUSTOMER_FIELD = "_CUSTOMER_FIELD"

    //SDKTopBar
    const val SCREEN_TITLE_TEXT = "SCREEN_TITLE_TEXT"
    const val SCREEN_BACK_BUTTON = "SCREEN_BACK_BUTTON"
    const val SCREEN_CLOSE_BUTTON = "SCREEN_CLOSE_BUTTON"

    //Payment overview
    const val COINS_VALUE_TEXT = "COINS_VALUE_TEXT"
    const val CURRENCY_VALUE_TEXT = "CURRENCY_VALUE_TEXT"
    const val TOTAL_PRICE_TITLE_TEXT = "TOTAL_PRICE_TITLE_TEXT"
    const val VAT_INCLUDED_LABEL_TEXT = "VAT_INCLUDED_LABEL_TEXT"
    const val PAYMENT_ID_LABEL_TEXT = "PAYMENT_ID_LABEL_TEXT"
    const val PAYMENT_ID_VALUE_TEXT = "PAYMENT_ID_VALUE_TEXT"
    const val PAYMENT_DESCRIPTION_LABEL_TEXT = "PAYMENT_DESCRIPTION_LABEL_TEXT"
    const val PAYMENT_DESCRIPTION_VALUE_TEXT = "PAYMENT_DESCRIPTION_VALUE_TEXT"
    const val ADDRESS_LABEL_TEXT = "ADDRESS_LABEL_TEXT"
    const val ADDRESS_VALUE_TEXT = "ADDRESS_VALUE_TEXT"
    const val PAYMENT_DETAILS_BUTTON = "PAYMENT_DETAILS_BUTTON"

    //Payment methods screen
    const val PAYMENT_METHOD_ITEM_TITLE = "PAYMENT_METHOD_ITEM_TITLE"
    const val PAYMENT_METHOD_ITEM_SECTION = "PAYMENT_METHOD_ITEM_SECTION"

    //Common card items
    const val CVV_INFO_BUTTON = "CVV_INFO_BUTTON"
    const val CVV_TEXT_FIELD = "CVV_TEXT_FIELD"
    const val EXPIRY_TEXT_FIELD = "EXPIRY_TEXT_FIELD"

    //Pan field
    const val PAN_TEXT_FIELD = "PAN_TEXT_FIELD"
    const val CARD_SCANNING_BUTTON = "CARD_SCANNING_BUTTON"
    const val DELETE_CARD_BUTTON = "DELETE_CARD_BUTTON"
}